Resources:
        ChillnnSFAMasterTable:
                Type: 'AWS::DynamoDB::Table'
                # DeletionPolicy: Retain # <= 本番ではこれ設定しないと死にます
                Properties:
                        AttributeDefinitions:
                                - AttributeName: PK
                                  AttributeType: S
                                - AttributeName: SK
                                  AttributeType: S
                                - AttributeName: uuid
                                  AttributeType: S
                                - AttributeName: pds
                                  AttributeType: S
                                - AttributeName: pacid
                                  AttributeType: S
                        BillingMode: PROVISIONED
                        # ContributorInsightsSpecification:
                        GlobalSecondaryIndexes:
                                - IndexName: ${self:custom.env.infra.${self:provider.stage}.DYNAMODB_MASTER_TABLE_UUID_INDEX_NAME}
                                  KeySchema:
                                          - AttributeName: uuid
                                            KeyType: HASH
                                  Projection:
                                          ProjectionType: ALL
                                  ProvisionedThroughput:
                                          ReadCapacityUnits: 1
                                          WriteCapacityUnits: 1
                                - IndexName: ${self:custom.env.infra.${self:provider.stage}.DYNAMODB_MASTER_TABLE_PDS_INDEX_NAME}
                                  KeySchema:
                                          - AttributeName: pds
                                            KeyType: HASH
                                          - AttributeName: PK
                                            KeyType: RANGE
                                  Projection:
                                          ProjectionType: ALL
                                  ProvisionedThroughput:
                                          ReadCapacityUnits: 1
                                          WriteCapacityUnits: 1
                                - IndexName: ${self:custom.env.infra.${self:provider.stage}.DYNAMODB_MASTER_TABLE_PACID_INDEX_NAME}
                                  KeySchema:
                                          - AttributeName: pacid
                                            KeyType: HASH
                                          - AttributeName: pds
                                            KeyType: RANGE
                                  Projection:
                                          ProjectionType: ALL
                                  ProvisionedThroughput:
                                          ReadCapacityUnits: 1
                                          WriteCapacityUnits: 1
                        KeySchema:
                                - AttributeName: PK
                                  KeyType: HASH
                                - AttributeName: SK
                                  KeyType: RANGE
                        # KinesisStreamSpecification:
                        # LocalSecondaryIndexes:
                        # PointInTimeRecoverySpecification:
                        ProvisionedThroughput:
                                ReadCapacityUnits: 1
                                WriteCapacityUnits: 1
                        # SSESpecification:
                        # StreamSpecification:
                        TableName: ${self:custom.env.infra.${self:provider.stage}.DYNAMODB_MASTER_TABLE_NAME}
                        Tags:
                                - Key: Name
                                  Value: ${self:provider.stage} Master
                        # TimeToLiveSpecification:
